### PR TITLE
Fix docker regressions

### LINKED ISSUE #343: docker.container regression
```shell
$ ./converge apply --local samples/dockerContainer.hcl
2016-10-03T11:17:27-04:00 |INFO| serving        addr=:47740 component=rpc
2016-10-03T11:17:27-04:00 |WARN| skipping module verification   component=client
2016-10-03T11:17:27-04:00 |INFO| got status     component=client file=samples/dockerContainer.hcl id=root/docker.container.nginx run=STARTED stage=APPLY
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x233635]

goroutine 78 [running]:
panic(0x608380, 0xc4200160c0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/asteris-llc/converge/apply.(*pipelineGen).applyNode(0xc4202b0140, 0x61d0c0, 0xc4202a75f0, 0x61d0c0, 0xc4202a75f0, 0x0, 0x0)
        /Users/ryan/Projects/golang/src/github.com/asteris-llc/converge/apply/pipeline.go:135 +0x145
github.com/asteris-llc/converge/apply.(*pipelineGen).(github.com/asteris-llc/converge/apply.applyNode)-fm(0x61d0c0, 0xc4202a75f0, 0x61d0c0, 0xc4202a75f0, 0x0, 0x0)
        /Users/ryan/Projects/golang/src/github.com/asteris-llc/converge/apply/pipeline.go:45 +0x3e
github.com/asteris-llc/converge/executor.Pipeline.Exec(0xc4202a2d40, 0x8, 0x8, 0x617e40, 0xc42029cbe0, 0x8, 0x63b260, 0xc420291f80, 0x0)
        /Users/ryan/Projects/golang/src/github.com/asteris-llc/converge/executor/pipeline.go:51 +0x5a
github.com/asteris-llc/converge/apply.execPipeline.func1(0xc4201453e0, 0x1b, 0xc4202a6e70, 0x0, 0x1b)
        /Users/ryan/Projects/golang/src/github.com/asteris-llc/converge/apply/apply.go:71 +0x10a
github.com/asteris-llc/converge/graph.NotifyPre.func1(0xc4201453e0, 0x1b, 0xc4202a6e70, 0xc4202919c8, 0xc420299cb0)
        /Users/ryan/Projects/golang/src/github.com/asteris-llc/converge/graph/notifier.go:30 +0x7f
github.com/asteris-llc/converge/graph.NotifyPost.func1(0xc4201453e0, 0x1b, 0xc4202a6e70, 0xc42029cbe0, 0xc420299e01)
        /Users/ryan/Projects/golang/src/github.com/asteris-llc/converge/graph/notifier.go:37 +0x54
github.com/asteris-llc/converge/graph.transform.func1(0xc4201453e0, 0x1b, 0x617e40, 0xc42029cbe0, 0xc42029cbe0, 0xc4202a2940)
        /Users/ryan/Projects/golang/src/github.com/asteris-llc/converge/graph/graph.go:554 +0x45
github.com/asteris-llc/converge/graph.dependencyWalk.func5(0xc4201453e0, 0x1b)
        /Users/ryan/Projects/golang/src/github.com/asteris-llc/converge/graph/graph.go:349 +0xb2c
created by github.com/asteris-llc/converge/graph.dependencyWalk.func3
        /Users/ryan/Projects/golang/src/github.com/asteris-llc/converge/graph/graph.go:264 +0x4f6
```

### PR DESCRIPTION
**Pull request by ryane**
fixes #343 

also brings back the docker-related validations that were removed in #321 (see #337)

### CODE REVIEW

File: resource/docker/container/preparer.go [hunk 1]
```diff
@@ -120,6 +120,12 @@ func (p *Preparer) Prepare(render resource.Renderer) (resource.Task, error) {
 }
 
 func validateContainer(container *Container) error {
+	if container.Name == "" {
```
Comment (BrianHicks) [inline resource/docker/container/preparer.go]: why are you validating these here rather than marking the field as required?

Comment (ryane) [inline resource/docker/container/preparer.go]: see #337. `required` is not enough to prevent someone from explicitly setting a field to an empty string

Comment (BrianHicks) [inline resource/docker/container/preparer.go]: Ah, right. Thanks

**Comment by ryane** [comment]
I found another issue where an incorrect status can be reported. 0186db6 should fix this

**Comment by ryane** [comment]
conflict-free now

**Comment by BrianHicks** [comment]
:gem:
